run unit and e2e test

diff --git a/.github/workflows/deploy-to-github-pages.yaml b/.github/workflows/deploy-to-github-pages.yaml
--- a/.github/workflows/deploy-to-github-pages.yaml
+++ b/.github/workflows/deploy-to-github-pages.yaml
@@ -6,32 +6,32 @@ on:
       - develop
 
 jobs:
-  # unit_tests:
-  #   name: Unit Test
-  #   runs-on: ubuntu-latest
-  #   steps:
-  #     - uses: actions/checkout@v4
-  #       with:
-  #         fetch-depth: 0
-  #     - uses: actions/setup-node@v4
-  #       with:
-  #         node-version: 18
-  #         cache: npm
+  unit_tests:
+    name: Unit Test
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v4
+        with:
+          fetch-depth: 0
+      - uses: actions/setup-node@v4
+        with:
+          node-version: 18
+          cache: npm
 
-  #     - name: Install dependencies
-  #       run: npm ci
+      - name: Install dependencies
+        run: npm ci
 
-  #     - name: Run Unit Tests
-  #       run: npm run test
+      - name: Run Unit Tests
+        run: npm run test
 
-  #     - name: Unit Test Report
-  #       uses: dorny/test-reporter@v1
-  #       if: success() || failure() # run this step even if previous step failed
-  #       with:
-  #         name: Unit Tests Reporter # Name of the check run which will be created
-  #         path: report/*.xml # Path to test results
-  #         reporter: jest-junit # Format of test results
-  #         fail-on-error: 'true' #  Set action as failed if test report contains any failed test
+      - name: Unit Test Report
+        uses: dorny/test-reporter@v1
+        if: success() || failure() # run this step even if previous step failed
+        with:
+          name: Unit Tests Reporter # Name of the check run which will be created
+          path: report/*.xml # Path to test results
+          reporter: jest-junit # Format of test results
+          fail-on-error: 'true' #  Set action as failed if test report contains any failed test
 
   e2e_tests:
     name: E2e Test For Core package
@@ -62,11 +62,11 @@ jobs:
           name: my-artifacts
           path: ./packages/core/test/scripts/*.out.txt
 
-      # - name: E2E Test Report
-      #   uses: dorny/test-reporter@v1
-      #   if: success() || failure() # run this step even if previous step failed
-      #   with:
-      #     name: E2E Core Tests Reporter # Name of the check run which will be created
-      #     path: report/e2e-core.xml # Path to test results
-      #     reporter: jest-junit # Format of test results
-      #     fail-on-error: 'true' #  Set action as failed if test report contains any failed test
+      - name: E2E Test Report
+        uses: dorny/test-reporter@v1
+        if: success() || failure() # run this step even if previous step failed
+        with:
+          name: E2E Core Tests Reporter # Name of the check run which will be created
+          path: report/e2e-core.xml # Path to test results
+          reporter: jest-junit # Format of test results
+          fail-on-error: 'true' #  Set action as failed if test report contains any failed test
